lib/absence_register_web/router.ex
defmodule AbsenceRegisterWeb.Router do
  use AbsenceRegisterWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(AbsenceRegisterWeb.Plugs.SetUser)
    plug(AbsenceRegisterWeb.Plugs.SetAdmin)
  end

  pipeline :require_auth do
    plug(:browser)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", AbsenceRegisterWeb do
    pipe_through(:browser)

    get("/", PageController, :index)
  end

  scope "/", AbsenceRegisterWeb do
    pipe_through(:require_auth)

    resources("/absences", AbsenceRequestController)
  end

  scope "/auth", AbsenceRegisterWeb do
    pipe_through(:browser)

    get("/google", AuthController, :request)
    get("/google/callback", AuthController, :callback)
    get("/signout", AuthController, :signout)
  end
end

lib/absence_register_web/views/layout_view.ex
defmodule AbsenceRegisterWeb.LayoutView do
  use AbsenceRegisterWeb, :view
end

lib/absence_register_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello AbsenceRegister!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <%= render "nav.html", conn: @conn %>
      </header>
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/absence_register_web/templates/layout/nav.html.eex
<div class="clearfix">
    <h3 class="text-muted pull-left">Absence Register</h3>
    <%= if @conn.assigns[:user] do
            render "nav_user.html", conn: @conn 
        else
            render "nav_guest.html", conn: @conn 
        end
    %>
</div>

lib/absence_register_web/templates/layout/nav_guest.html.eex
<nav class="pull-right">
    <ul class="nav ">
        <li class="active"><a href="/auth/google">Sign In</a></li>
    </ul>
</nav>

lib/absence_register_web/templates/layout/nav_user.html.eex
<p class="text-right">
    Welcome <b><%= @conn.assigns.user.name %></b>
</p>
<nav>
    <ul class="nav navbar-nav navbar-right">
        <li>
            <a href="/">Home</a>    
        </li>
        <li>
            <%= link "Absence Requests", to: absence_request_path(@conn, :index) %>    
        </li>
        <li class="active">
            <%= link "Sign Out", to: auth_path(@conn, :signout) %>    
        </li>
    </ul>
</nav>